### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by Arcanocito** [bertrik/ttn-gateway-collector#4]
Hello, when attempting the 'docker-compose up', the build fails with the following error message: 

Step 6/8 : ADD ttn-gateway-collector/build/distributions/ttn-gateway-collector.tar /opt/
ERROR: Service 'java' failed to build: ADD failed: file not found in build context or excluded by .dockerignore: stat ttn-gateway-collector/build/distributions/ttn-gateway-collector.tar: file does not exist

I cannot find the ttn-gateway-collector.tar file in any of the provided directorys.

**Comment by bertrik** [comment]
What is happening is that docker tries to *build* the image from scratch, instead of just pulling it from the github container registry. So somehow the 'build: ..' line in docker-compose.yaml takes precendence over the 'image: ghcr.io/bertrik/ttn-gateway-collector' line.

To be honest, I don't know why and under what conditions docker (or docker-compose) behaves this way. I believe different versions of docker have different behaviour in this regard. I cannot reproduce this on my development machine, but I have seen this on other machines.

Things you can try:
1) first run 'docker-compose pull' to manually/explicitly pull the image from the registry, then use 'docker-compose up'
2) temporarily remove the 'build: ..' line from docker-compose.yaml, then try 'docker-compose up' again.
3) or, just actually build the java image (although the point was to avoid this by using docker), by running './gradlew assemble' in the root directory of the project, then 'docker-compose up' in the docker directory. This requires the java-17 JDK though.

**Comment by Arcanocito** [comment]
Removing the 'build: ..' then running 'docker-compose pull', then 'docker-compose up' got it to work :3 Thank you!
